deny = [
    # Prevent spelling mistakes in lints
    'unknown_lints',

    # Use the default groups:
    # correctness, suspicious, style, complexity, perf
    'clippy::all',
    
    # Require documentation
     'missing_docs',

    # Common mistakes
    'unused_variables',
    'unused_imports',
    'dead_code',
    'unused_extern_crates',
    'unused_must_use',
    'unreachable_patterns',
    'let_underscore_drop',

    'clippy::cloned_instead_of_copied',
    'clippy::create_dir',
    'clippy::dbg_macro',
    'clippy::else_if_without_else',
    'clippy::enum_glob_use',
    'clippy::inline_always',
    'clippy::match_on_vec_items',
    'clippy::match_wild_err_arm',

    # Style preferences
    'clippy::explicit_into_iter_loop',
    'clippy::explicit_iter_loop',
    'clippy::if_not_else',
    'clippy::match_bool',
    'clippy::needless_pass_by_value',
    'clippy::range_plus_one',
    'clippy::struct_excessive_bools',
    'clippy::too_many_lines',
    'clippy::trivially_copy_pass_by_ref',

    # Casting mistakes
    'clippy::cast_lossless',
    'clippy::cast_possible_truncation',
    'clippy::cast_possible_wrap',
    'clippy::cast_precision-loss',
    'clippy::cast_sign_loss'
]

warn = [
    'clippy::uninlined_format_args',
    'clippy::too_many_arguments',
]

allow = [
    'clippy::too_long_first_doc_paragraph',
]