binop_separator = "Back"
comment_width = 120
edition = "2021"
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = false
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 120
newline_style = "Native"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
space_before_colon = false
struct_lit_single_line = true
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "default"
use_try_shorthand = true
where_single_line = true
wrap_comments = true
ignore=[]
