---
name: Formatting, lints, and code checks

'on':
  workflow_dispatch:
  push:
    branches:
      - "ci-*"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  merge_group:

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install components
        uses: dtolnay/rust-toolchain@master
        with:
          components: clippy, rustfmt
          toolchain: nightly
      - name: Toolchain thumbv8m.main-none-eabi
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: thumbv8m.main-none-eabi
      - name: Check formatting
        run: cargo +nightly fmt --all -- --check
      - name: Install linter
        run: cargo install cargo-lints
      - name: Run linter
        run: cargo +nightly lints clippy --all-targets --all-features
      - name: Check code
        run: cargo +stable check --release --all-targets
      - name: Check code (no default features)
        run: cargo +stable check --release --no-default-features
      - name: Check benchmarks
        run: cargo +nightly check --benches
      - name: cargo machete
        run: |
          cargo install cargo-machete@0.7.0
          cargo machete
      - name: cargo vet
        run: |
          cargo install cargo-vet@0.10.0 --locked
          cargo vet
