name: Code Coverage
on:
  push:
    branches:
      - main
jobs:
  grcov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake
      - name: Download Rust
        uses: actions-rs/toolchain@v1
      - name: Build
        run: cargo test --all-features --no-fail-fast --lib
        env:
          CARGO_FEATURE_FFI: '0'
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - name: Run test coverage
        id: coverage
        uses: actions-rs/grcov@v0.1
      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage.outputs.report }}
